const fs = require('fs')

const content = [
  "'use client'",
  "import { useEffect, useState } from 'react'",
  "import { supabase } from './lib/supabase'",
  "import Link from 'next/link'",
  "import { TrendingUp, TrendingDown, Clock, AlertCircle, Users, Bell } from 'lucide-react'",
  "import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Legend } from 'recharts'",
  "",
  "type Alerta = {",
  "  id: string",
  "  descricao: string",
  "  valor: number",
  "  vencimento: string",
  "  tipo: string",
  "}",
  "",
  "export default function Home() {",
  "  const hoje = new Date()",
  "  const mesAtual = `${hoje.getFullYear()}-${String(hoje.getMonth() + 1).padStart(2, '0')}`",
  "",
  "  const [mes, setMes] = useState(mesAtual)",
  "  const [receitas, setReceitas] = useState(0)",
  "  const [despesas, setDespesas] = useState(0)",
  "  const [aReceber, setAReceber] = useState(0)",
  "  const [aPagar, setAPagar] = useState(0)",
  "  const [salariosCaio, setSalariosCaio] = useState(0)",
  "  const [salariosCharles, setSalariosCharles] = useState(0)",
  "  const [salariosBruno, setSalariosBruno] = useState(0)",
  "  const [grafico, setGrafico] = useState<any[]>([])",
  "  const [alertas, setAlertas] = useState<Alerta[]>([])",
  "",
  "  function getMeses() {",
  "    const meses = []",
  "    for (let i = 5; i >= 0; i--) {",
  "      const d = new Date(hoje.getFullYear(), hoje.getMonth() - i, 1)",
  "      const valor = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`",
  "      const label = d.toLocaleString('pt-BR', { month: 'short' })",
  "      meses.push({ valor, label })",
  "    }",
  "    return meses",
  "  }",
  "",
  "  useEffect(() => {",
  "    async function carregar() {",
  "      const inicio = `${mes}-01`",
  "      const fim = `${mes}-31`",
  "",
  "      const { data: r } = await supabase.from('receitas').select('valor').gte('data', inicio).lte('data', fim)",
  "      if (r) setReceitas(r.reduce((acc, x) => acc + x.valor, 0))",
  "",
  "      const { data: d } = await supabase.from('despesas').select('valor').gte('data', inicio).lte('data', fim)",
  "      if (d) setDespesas(d.reduce((acc, x) => acc + x.valor, 0))",
  "",
  "      const { data: cr } = await supabase.from('contas_receber').select('valor').eq('status', 'pendente').gte('vencimento', inicio).lte('vencimento', fim)",
  "      if (cr) setAReceber(cr.reduce((acc, x) => acc + x.valor, 0))",
  "",
  "      const { data: cp } = await supabase.from('contas_pagar').select('valor').eq('status', 'pendente').gte('vencimento', inicio).lte('vencimento', fim)",
  "      if (cp) setAPagar(cp.reduce((acc, x) => acc + x.valor, 0))",
  "",
  "      const { data: s } = await supabase.from('salarios_socios').select('socio, valor').eq('mes', mes)",
  "      if (s) {",
  "        setSalariosCaio(s.filter(x => x.socio === 'Caio').reduce((acc, x) => acc + x.valor, 0))",
  "        setSalariosCharles(s.filter(x => x.socio === 'Charles').reduce((acc, x) => acc + x.valor, 0))",
  "        setSalariosBruno(s.filter(x => x.socio === 'Bruno').reduce((acc, x) => acc + x.valor, 0))",
  "      }",
  "",
  "      const meses = getMeses()",
  "      const dadosGrafico = await Promise.all(meses.map(async m => {",
  "        const ini = `${m.valor}-01`",
  "        const fim2 = `${m.valor}-31`",
  "        const { data: rec } = await supabase.from('receitas').select('valor').gte('data', ini).lte('data', fim2)",
  "        const { data: desp } = await supabase.from('despesas').select('valor').gte('data', ini).lte('data', fim2)",
  "        return {",
  "          mes: m.label,",
  "          Receitas: rec ? rec.reduce((acc, x) => acc + x.valor, 0) : 0,",
  "          Despesas: desp ? desp.reduce((acc, x) => acc + x.valor, 0) : 0,",
  "        }",
  "      }))",
  "      setGrafico(dadosGrafico)",
  "",
  "      const daqui7 = new Date()",
  "      daqui7.setDate(daqui7.getDate() + 7)",
  "      const daqui7str = daqui7.toISOString().split('T')[0]",
  "      const hojestr = hoje.toISOString().split('T')[0]",
  "",
  "      const { data: alertasPagar } = await supabase.from('contas_pagar').select('id, descricao, valor, vencimento').eq('status', 'pendente').lte('vencimento', daqui7str).gte('vencimento', hojestr)",
  "      const { data: alertasReceber } = await supabase.from('contas_receber').select('id, descricao, valor, vencimento').eq('status', 'pendente').lte('vencimento', daqui7str).gte('vencimento', hojestr)",
  "",
  "      const lista: Alerta[] = [",
  "        ...(alertasPagar || []).map(x => ({ ...x, tipo: 'pagar' })),",
  "        ...(alertasReceber || []).map(x => ({ ...x, tipo: 'receber' })),",
  "      ]",
  "      setAlertas(lista)",
  "    }",
  "    carregar()",
  "  }, [mes])",
  "",
  "  const saldo = receitas - despesas",
  "",
  "  const cards = [",
  "    { titulo: 'Receitas', valor: receitas, cor: 'text-emerald-400', bg: 'bg-emerald-400/10', icon: TrendingUp, href: '/receitas' },",
  "    { titulo: 'Despesas', valor: despesas, cor: 'text-rose-400', bg: 'bg-rose-400/10', icon: TrendingDown, href: '/despesas' },",
  "    { titulo: 'A Receber', valor: aReceber, cor: 'text-blue-400', bg: 'bg-blue-400/10', icon: Clock, href: '/contas-receber' },",
  "    { titulo: 'A Pagar', valor: aPagar, cor: 'text-orange-400', bg: 'bg-orange-400/10', icon: AlertCircle, href: '/contas-pagar' },",
  "  ]",
  "",
  "  const salarios = [",
  "    { nome: 'Caio', valor: salariosCaio },",
  "    { nome: 'Charles', valor: salariosCharles },",
  "    { nome: 'Bruno', valor: salariosBruno },",
  "  ]",
  "",
  "  return (",
  "    <main className=\"min-h-screen bg-[#0f1117] p-8\">",
  "      <div className=\"max-w-4xl mx-auto\">",
  "",
  "        <div className=\"flex items-center justify-between mb-10\">",
  "          <div>",
  "            <h1 className=\"text-3xl font-bold text-white\">Dashboard</h1>",
  "            <p className=\"text-gray-500 mt-1\">Visao geral das suas financas</p>",
  "          </div>",
  "          <input type=\"month\" value={mes} onChange={e => setMes(e.target.value)} className=\"bg-[#1a1d2e] border border-[#2a2d3e] rounded-xl px-4 py-2 text-white focus:outline-none focus:border-indigo-500\" />",
  "        </div>",
  "",
  "        {alertas.length > 0 && (",
  "          <div className=\"bg-yellow-400/5 border border-yellow-400/20 rounded-2xl p-5 mb-8\">",
  "            <div className=\"flex items-center gap-2 mb-4\">",
  "              <Bell className=\"w-4 h-4 text-yellow-400\" />",
  "              <p className=\"text-yellow-400 font-semibold text-sm\">Vencem nos proximos 7 dias</p>",
  "            </div>",
  "            <div className=\"space-y-2\">",
  "              {alertas.map(a => (",
  "                <div key={a.id + a.tipo} className=\"flex items-center justify-between bg-[#0f1117] rounded-xl px-4 py-3\">",
  "                  <div className=\"flex items-center gap-3\">",
  "                    <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${a.tipo === 'pagar' ? 'bg-rose-400/10 text-rose-400' : 'bg-blue-400/10 text-blue-400'}`}>",
  "                      {a.tipo === 'pagar' ? 'A Pagar' : 'A Receber'}",
  "                    </span>",
  "                    <p className=\"text-white text-sm\">{a.descricao}</p>",
  "                  </div>",
  "                  <div className=\"text-right\">",
  "                    <p className=\"text-white font-semibold text-sm\">R$ {a.valor.toFixed(2)}</p>",
  "                    <p className=\"text-gray-500 text-xs\">{new Date(a.vencimento + 'T00:00:00').toLocaleDateString('pt-BR')}</p>",
  "                  </div>",
  "                </div>",
  "              ))}",
  "            </div>",
  "          </div>",
  "        )}",
  "",
  "        <div className=\"bg-[#1a1d2e] border border-[#2a2d3e] rounded-2xl p-6 mb-8\">",
  "          <p className=\"text-gray-400 text-sm mb-1\">Saldo do mes</p>",
  "          <p className={`text-4xl font-bold ${saldo >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>",
  "            R$ {saldo.toFixed(2)}",
  "          </p>",
  "        </div>",
  "",
  "        <div className=\"grid grid-cols-2 gap-4 mb-8\">",
  "          {cards.map(card => {",
  "            const Icon = card.icon",
  "            return (",
  "              <Link key={card.titulo} href={card.href} className=\"bg-[#1a1d2e] border border-[#2a2d3e] rounded-2xl p-6 hover:border-indigo-500 transition-colors\">",
  "                <div className={`w-10 h-10 ${card.bg} rounded-xl flex items-center justify-center mb-4`}>",
  "                  <Icon className={`w-5 h-5 ${card.cor}`} />",
  "                </div>",
  "                <p className=\"text-gray-400 text-sm\">{card.titulo}</p>",
  "                <p className={`text-2xl font-bold mt-1 ${card.cor}`}>R$ {card.valor.toFixed(2)}</p>",
  "              </Link>",
  "            )",
  "          })}",
  "        </div>",
  "",
  "        <div className=\"bg-[#1a1d2e] border border-[#2a2d3e] rounded-2xl p-6 mb-8\">",
  "          <p className=\"text-white font-semibold mb-6\">Receitas x Despesas (ultimos 6 meses)</p>",
  "          <ResponsiveContainer width=\"100%\" height={220}>",
  "            <BarChart data={grafico} barGap={4}>",
  "              <XAxis dataKey=\"mes\" tick={{ fill: '#6b7280', fontSize: 12 }} axisLine={false} tickLine={false} />",
  "              <YAxis tick={{ fill: '#6b7280', fontSize: 12 }} axisLine={false} tickLine={false} tickFormatter={v => `R$${v}`} />",
  "              <Tooltip contentStyle={{ backgroundColor: '#0f1117', border: '1px solid #2a2d3e', borderRadius: 12, color: '#fff' }} formatter={(v: any) => `R$ ${Number(v).toFixed(2)}`} />",
  "              <Legend wrapperStyle={{ color: '#9ca3af', fontSize: 12 }} />",
  "              <Bar dataKey=\"Receitas\" fill=\"#34d399\" radius={[6, 6, 0, 0]} />",
  "              <Bar dataKey=\"Despesas\" fill=\"#f87171\" radius={[6, 6, 0, 0]} />",
  "            </BarChart>",
  "          </ResponsiveContainer>",
  "        </div>",
  "",
  "        <div className=\"bg-[#1a1d2e] border border-[#2a2d3e] rounded-2xl p-6\">",
  "          <div className=\"flex items-center justify-between mb-5\">",
  "            <div className=\"flex items-center gap-3\">",
  "              <div className=\"w-10 h-10 bg-purple-400/10 rounded-xl flex items-center justify-center\">",
  "                <Users className=\"w-5 h-5 text-purple-400\" />",
  "              </div>",
  "              <p className=\"text-white font-semibold\">Salario dos Socios</p>",
  "            </div>",
  "            <Link href=\"/salarios\" className=\"text-indigo-400 text-sm hover:text-indigo-300 transition-colors\">Ver tudo</Link>",
  "          </div>",
  "          <div className=\"grid grid-cols-3 gap-4\">",
  "            {salarios.map(s => (",
  "              <div key={s.nome} className=\"bg-[#0f1117] rounded-xl p-4\">",
  "                <p className=\"text-gray-400 text-sm\">{s.nome}</p>",
  "                <p className=\"text-purple-400 text-xl font-bold mt-1\">R$ {s.valor.toFixed(2)}</p>",
  "              </div>",
  "            ))}",
  "          </div>",
  "        </div>",
  "",
  "      </div>",
  "    </main>",
  "  )",
  "}"
].join('\n')

fs.writeFileSync('app/page.tsx', content, 'utf8')
console.log('Alertas de vencimento adicionados com sucesso!')